'-----------------------------------------------------------
'MINNESOTA EDUCATIONAL COMPUTING CONSORTIUM STAFF
'PROGRAMMING REVISIONS BY DON RAWITSCH - 1975
'CURRENT VERSION - 09/2025 - Ariel Palazzesi
'-----------------------------------------------------------
PRINT : PRINT 
Titulo("OREGON TRAIL")
PRINT : COLOR RGB(white)
PRINT "                    _____________ "
PRINT "                   (   (  |  )   )"
PRINT "                    (  (  |  )  ) "
PRINT "     (__)         __|___________| "
PRINT "     (oo)------/   |            | "
PRINT "     (__)    ||====|____________| "
PRINT "        ||---||      (X)    (x)   "  
PRINT : COLOR RGB(green)
PRINT
PRINT
PRINT CENTRAR$("Created by Don Rawitsch,")
PRINT CENTRAR$("Bill Heinemann and Paul Dillenberger.")
PRINT
PRINT CENTRAR$("2025 Ported to PicoCalc") 
PRINT CENTRAR$("by Ariel Palazzesi.")

PRINT:PRINT:PRINT
INPUT "DO YOU NEED INSTRUCTIONS (Y/N)"; a1$
ValidarSioNo
IF SiNo = 0 THEN
  CLS
  Titulo("INSTRUCTIONS")
  PRINT
  PRINT "THIS PROGRAM SIMULATES A TRIP OVER THE"
  PRINT "OREGON TRAIL FROM INDEPENDENCE, MISSOURI"
  PRINT "TO OREGON CITY, OREGON IN 1847."
  PRINT "YOUR FAMILY OF FIVE WILL COVER THE 2000"
  PRINT "MILE OREGON TRAIL IN 5-6 MONTHS. "
  COLOR RGB(gold) : PRINT "IF YOU MAKE IT ALIVE"
  COLOR RGB(green)
  PRINT
  PRINT "YOU HAD SAVED $900 TO SPEND FOR THE TRIP"
  PRINT "AND YOU'VE JUST PAID $200 FOR A WAGON."
  PRINT "YOU WILL NEED TO SPEND THE REST OF YOUR"
  PRINT "MONEY ON THE FOLLOWING ITEMS:" 
  PRINT
  COLOR RGB(gold) : PRINT "OXEN: "; : COLOR RGB(green)
  PRINT "YOU CAN SPEND $200-$300 ON YOUR"
  PRINT "TEAM. THE MORE YOU SPEND, THE FASTER"
  PRINT "YOU'LL GO, BECAUSE YOU'LL HAVE BETTER"
  PRINT "ANIMALS." 
  PRINT
  COLOR RGB(gold) : PRINT "FOOD: "; : COLOR RGB(green)
  PRINT "THE MORE YOU HAVE, THE LESS"
  PRINT "CHANCE THERE IS OF GETTING SICK."
  PresionarTecla
  CLS
  COLOR RGB(gold) : PRINT "AMMUNITION: "; : COLOR RGB(green)
  PRINT "$1 BUYS A BELT OF 50 BULLETS"
  PRINT "YOU WILL NEED BULLETS FOR ATTACKS BY"
  PRINT "ANIMALS AND BANDITS, AND FOR HUNTING"
  PRINT "FOOD."
  PRINT
  COLOR RGB(gold) : PRINT "CLOTHING: "; : COLOR RGB(green)
  PRINT "THIS IS ESPECIALLY IMPORTANT"
  PRINT "FOR THE COLD WEATHER YOU WILL ENCOUNTER"
  PRINT "WHEN CROSSING THE MOUNTAINS."
  PRINT
  COLOR RGB(gold) : PRINT "MISCELLANEOUS SUPPLIES: "; : COLOR RGB(green)
  PRINT "THIS INCLUDES"
  PRINT "MEDICINE AND OTHER THINGS YOU WILL NEED"
  PRINT "FOR SICKNESS AND EMERGENCY REPAIRS."
  PRINT
  PRINT "YOU CAN SPEND ALL YOUR MONEY BEFORE YOU"
  PRINT "START YOUR TRIP -OR YOU CAN SAVE SOME OF"
  PRINT "YOUR CASH TO SPEND AT FORTS ALONG THE"
  PRINT "WAY WHEN YOU RUN LOW."
  PRINT "HOWEVER, ITEMS COST MORE AT THE FORTS."
  PRINT "YOU CAN ALSO GO HUNTING ALONG THE WAY TO"
  PRINT "MORE FOOD."
  PresionarTecla
  CLS  
  PRINT "WHENEVER YOU HAVE TO USE YOUR TRUSTY"
  PRINT "RIFLE ALONG THE WAY, YOU WILL SEE THE"
  PRINT "WORDS: TYPE BANG. THE FASTER YOU TYPE"
  PRINT "IN THE WORD 'BANG' AND HIT THE 'RETURN'"
  PRINT "KEY, THE BETTER LUCK YOU'LL HAVE WITH"
  PRINT "YOUR GUN."
  PRINT
  PRINT "WHEN ASKED TO ENTER MONEY AMOUNTS, "
  PRINT "DON'T USE A '$'."
  PRINT
  COLOR RGB(gold)
  PRINT CENTRAR$("GOOD LUCK!!!")
  COLOR RGB(green)
  PresionarTecla
  CLS
END IF

'--------------------------------------
' COMPRAS INICIALES
'--------------------------------------
COMPRAS_INICIALES:
DO 
  X1=-1
  K8=0: S4=0: F1=0: F2=0: M=0: M9=0: D3=0

  PRINT
  Titulo("INITIAL PURCHASES:")
  PRINT

  DO
    PRINT "HOW MUCH DO YOU WANT TO SPEND ON YOUR"
    INPUT "OXEN TEAM"; A
    IF A < 200 THEN
      PRINT "NOT ENOUGH."
    ELSEIF A > 300 THEN
      PRINT "TOO MUCH."
    ELSE
      EXIT DO
    ENDIF
  LOOP

  DO
    PRINT "HOW MUCH DO YOU WANT TO SPEND ON"
    INPUT "FOOD"; F
    IF F < 0 THEN
      PRINT "IMPOSSIBLE."
    ELSE
      EXIT DO
    ENDIF
  LOOP

  DO
    PRINT "HOW MUCH DO YOU WANT TO SPEND ON"
    INPUT "AMMUNITION"; B
    IF B < 0 THEN
      PRINT "IMPOSSIBLE."
    ELSE
      EXIT DO
    ENDIF
  LOOP

  DO
    PRINT "HOW MUCH DO YOU WANT TO SPEND ON"
    INPUT "CLOTHING"; C
    IF C < 0 THEN
      PRINT "IMPOSSIBLE."
    ELSE
      EXIT DO
    ENDIF
  LOOP

  DO
    PRINT "HOW MUCH DO YOU WANT TO SPEND ON"
    INPUT "MISCELANEOUS SUPPLIES"; M1
    IF M1 < 0 THEN
      PRINT "IMPOSSIBLE."
    ELSE
      EXIT DO
    ENDIF
  LOOP

  ' presupuesto total y validacion
  T = 700 - A - F - B - C - M1
  IF T < 0 THEN
    PRINT "YOU OVERSPENT--YOU ONLY HAD $700 TO"
    PRINT "SPEND.  BUY AGAIN."
    PresionarTecla
    CLS
  ELSE
    EXIT DO
  ENDIF
LOOP

B = 50 * B '1 dolar = 50 balas
PRINT
PRINT "AFTER ALL YOUR PURCHASES, YOU NOW HAVE"
PRINT T;" DOLLARS LEFT"
COLOR RGB(white) : 
PRINT STRING$(40,"_")
PRINT 
Titulo("MONDAY MARCH 29 1847")
PRINT

'--------------------------------------
' INICIO DEL JUEGO
'--------------------------------------
GOTO COMIENZO_TURNO

'--------------------------------------
' FECHA DE CADA QUINCENA
'--------------------------------------
FECHA_QUINCENA:
IF M >= 2040 OR D3 > 17 THEN GOTO LLEGADA_FINAL

D3 = D3 + 1
fecha_aux$ = "MONDAY "
SELECT CASE D3
  CASE 1:  fecha_aux$ = fecha_aux$ + "APRIL 12  "
  CASE 2:  fecha_aux$ = fecha_aux$ + "APRIL 26 "
  CASE 3:  fecha_aux$ = fecha_aux$ + "MAY 10 "
  CASE 4:  fecha_aux$ = fecha_aux$ + "MAY 24 "
  CASE 5:  fecha_aux$ = fecha_aux$ + "JUNE 7 "
  CASE 6:  fecha_aux$ = fecha_aux$ + "JUNE 21 "
  CASE 7:  fecha_aux$ = fecha_aux$ + "JULY 5 "
  CASE 8:  fecha_aux$ = fecha_aux$ + "JULY 19 "
  CASE 9:  fecha_aux$ = fecha_aux$ + "AUGUST 2 "
  CASE 10: fecha_aux$ = fecha_aux$ + "AUGUST 16 "
  CASE 11: fecha_aux$ = fecha_aux$ + "AUGUST 31 "
  CASE 12: fecha_aux$ = fecha_aux$ + "SEPTEMBER 13 "
  CASE 13: fecha_aux$ = fecha_aux$ + "SEPTEMBER 27 "
  CASE 14: fecha_aux$ = fecha_aux$ + "OCTOBER 11 "
  CASE 15: fecha_aux$ = fecha_aux$ + "OCTOBER 25 "
  CASE 16: fecha_aux$ = fecha_aux$ + "NOVEMBER 8 "
  CASE 17: fecha_aux$ = fecha_aux$ + "NOVEMBER 22 "
END SELECT

fecha_aux$ = fecha_aux$ + "1847"
COLOR RGB(white) : 
PRINT STRING$(40,"_")
PRINT 
Titulo(fecha_aux$)
PRINT

'GOTO COMIENZO_TURNO

'--------------------------------------
' COMIENZO DE CADA TURNO
'--------------------------------------
COMIENZO_TURNO:
PRINT
IF F < 0 THEN F=0
IF B < 0 THEN B=0
IF C < 0 THEN C=0
IF M1 < 0 THEN M1=0
IF F < 12 THEN 
  PRINT "YOU'D BETTER DO SOME HUNTING OR BUY FOOD"
  PRINT "AND SOON!!!!"
END IF

F=INT(F): B=INT(B): C=INT(C): M1=INT(M1)
T=INT(T): M=INT(M): M2=M

IF NOT (S4=1 OR K8=1) THEN GOTO MOSTRAR_MILLAJE
T=T-20
IF T<0 THEN GOTO SIN_DINERO_MEDICO
PRINT "DOCTOR'S BILL IS $20"
K8=0: S4=0

MOSTRAR_MILLAJE:
IF M9=1 THEN
  PRINT "TOTAL MILEAGE IS 950"
  M9=0
ELSE
    PRINT "TOTAL MILEAGE IS";M
END IF

PRINT " FOOD  BULLETS  CLOTH  MISC.SUPP.  CASH"
PRINT TAB(2);F;
PRINT TAB(9);B;
PRINT TAB(17);C;
PRINT TAB(25);M1;
PRINT TAB(35);"$";T
PRINT

' decision de accion
IF X1=-1 THEN
  X1=X1*-1
  PRINT
  PRINT "DO YOU WANT TO:"
  PRINT "   (1) STOP AT THE NEXT FORT"
  PRINT "   (2) HUNT"
  PRINT "   (3) CONTINUE"
  INPUT "YOUR CHOICE";X

  IF X<1 OR X>3 THEN X=3
ELSE
  PRINT
  PRINT "DO YOU WANT TO:"
  PRINT "   (1) HUNT"
  PRINT "   (2) CONTINUE"
  INPUT "YOUR CHOICE";X

  X=X+1
  IF X=3 AND B<=39 THEN
    PRINT
    PRINT "TOUGH---YOU NEED MORE BULLETS TO GO"
    PRINT "HUNTING"
    GOTO COMIENZO_TURNO
  END IF
  X1=X1*-1
END IF

SELECT CASE X
  CASE 1: GOTO PARAR_EN_FUERTE
  CASE 2: GOTO CAZAR
  CASE ELSE: GOTO CONTINUAR_RUTA
END SELECT

'--------------------------------------
' PARADA EN FUERTE
'--------------------------------------
PARAR_EN_FUERTE:
PRINT
PRINT "ENTER WHAT YOU WISH TO SPEND ON THE"
PRINT "FOLLOWING"
PRINT

PRINT "FOOD";
GOSUB ENTRADA_COMPRA
F=F + (2/3)*P

PRINT "AMMUNITION";
GOSUB ENTRADA_COMPRA
B=INT(B + (2/3)*P*50)

PRINT "CLOTHING";
GOSUB ENTRADA_COMPRA
C=C + (2/3)*P

PRINT "MISCELLANEOUS SUPPLIES";
GOSUB ENTRADA_COMPRA
M1=M1 + (2/3)*P

M=M-45
GOTO CONTINUAR_RUTA

'-------------------------------------
' CAZA
'-------------------------------------
CAZAR:
IF B<=39 THEN
  PRINT "TOUGH---YOU NEED MORE BULLETS TO GO"
  PRINT "HUNTING"
  GOTO COMIENZO_TURNO
END IF

M=M-45
GOSUB SUBRUTINA_DISPARO

IF B1 > 2 THEN
  IF 100*RND(0) < 13*B1 THEN
    PRINT "SORRY---NO LUCK TODAY"
  ELSE
    F=F + 48 - 2*B1
    PRINT "NICE SHOT--RIGHT THROUGH THE NECK"
    PRINT "FEAST TONIGHT!!"
    B=B - 10 - 3*B1
  END IF
ELSE
  PRINT "RIGHT BETWEEN THE EYES---YOU GOT A"
  PRINT "BIG ONE!!"
  F=F + 52 + RND(0)*6
  B=B - 10 - RND(0)*4
END IF

GOTO CONTINUAR_RUTA

'--------------------------------------
' CONTINUAR RUTA (COMER, EVENTOS, ETC.)
'--------------------------------------
CONTINUAR_RUTA:
IF F < 13 THEN GOTO SIN_COMIDA

PRINT
PRINT "DO YOU WANT TO EAT:"
PRINT "   (1) POORLY"
PRINT "   (2) MODERATELY"
PRINT "   (3) WELL"
INPUT "YOUR CHOICE";E

IF E<1 OR E>3 THEN GOTO CONTINUAR_RUTA
E=INT(E)
F=F - 8 - 5*E
IF F < 0 THEN
  F=F + 8 + 5*E
  PRINT "YOU CAN'T EAT THAT WELL"
  GOTO CONTINUAR_RUTA
END IF

' avanzar
M = M + 200 + (A-220)/5 + 10*RND(0)
L1=0: C1=0

' jinetes
IF RND(0)*10 <= ((M/100-4)^2+72)/((M/100-4)^2+12)-1 THEN GOTO JINETES
GOTO EVENTOS

'--------------------------------------
' JINETES ADELANTE
'--------------------------------------
JINETES:
PRINT
PRINT "RIDERS AHEAD.  THEY "
S5=0
IF RND(0) < .8 THEN
  ' nada
ELSE
  PRINT "DON'T ";
  S5=1
END IF
PRINT "LOOK HOSTILE"
PRINT
PRINT "TACTICS:"
PRINT "   (1) RUN"
PRINT "   (2) ATTACK"
PRINT "   (3) CONTINUE"
PRINT "   (4) CIRCLE WAGONS"
PRINT
PRINT "IF YOU RUN YOU'LL GAIN TIME BUT WEAR"
PRINT "DOWN YOUR OXEN"
PRINT "IF YOU CIRCLE YOU'LL LOSE TIME"
PRINT

IF RND(0) <= .2 THEN S5=1-S5

INPUT "YOUR CHOICE";T1
IF T1<1 OR T1>4 THEN GOTO JINETES
T1=INT(T1)

IF S5=1 THEN GOTO JINETES_AMIGOS

' hostiles (S5=0)
IF T1=1 THEN
  M=M+20: M1=M1-15: B=B-150: A=A-40
  GOTO JINETES_FIN
ELSEIF T1=2 THEN
  GOSUB SUBRUTINA_DISPARO
  B=B - B1*40 - 80
  IF B1<=1 THEN
    PRINT "NICE SHOOTING---YOU DROVE THEM OFF"
    GOTO JINETES_FIN
  ELSEIF B1>4 THEN
    PRINT "LOUSY SHOT---YOU GOT KNIFED"
    K8=1
    PRINT "YOU HAVE TO SEE OL' DOC BLANCHARD"
    GOTO JINETES_FIN
  ELSE
    PRINT "KINDA SLOW WITH YOUR COLT .45"
    GOTO JINETES_FIN
  END IF
ELSEIF T1=3 THEN
  IF RND(0) <= .8 THEN
    B=B-150: M1=M1-15
  ELSE
    PRINT "THEY DID NOT ATTACK"
    GOTO EVENTOS
  END IF
  GOTO JINETES_FIN
ELSE
  GOSUB SUBRUTINA_DISPARO
  B=B - B1*30 - 80
  M=M-25
  IF B < 0 THEN
    PRINT "YOU RAN OUT OF BULLETS AND GOT"
    PRINT "MASSACRED BY THE RIDERS"
    GOTO MUERTE
  END IF
  GOTO JINETES_FIN2
END IF

JINETES_AMIGOS:
IF T1=1 THEN
  M=M+15: A=A-10
ELSEIF T1=2 THEN
  M=M-5: B=B-100
ELSEIF T1=3 THEN
  ' nada
ELSE
  M=M-20
END IF

JINETES_FIN:
IF S5=1 THEN
  PRINT "RIDERS WERE FRIENDLY, BUT CHECK FOR"
  PRINT "POSSIBLE LOSSES"
ELSE
  PRINT "RIDERS WERE HOSTILE--CHECK FOR LOSSES"
END IF
IF B < 0 THEN
  PRINT "YOU RAN OUT OF BULLETS AND GOT"
  PRINT "MASSACRED BY THE RIDERS"
  GOTO MUERTE
END IF
GOTO EVENTOS

JINETES_FIN2:
IF S5=1 THEN
  PRINT "RIDERS WERE FRIENDLY, BUT CHECK FOR"
  PRINT "POSSIBLE LOSSES"
ELSE
  PRINT "RIDERS WERE HOSTILE--CHECK FOR LOSSES"
END IF
IF B < 0 THEN
  PRINT "YOU RAN OUT OF BULLETS AND GOT"
  PRINT "MASSACRED BY THE RIDERS"
  GOTO MUERTE
END IF
'--------------------------------------
' SELECCION DE EVENTOS
'--------------------------------------
EVENTOS:
D1=0
RESTORE
R1=100*RND(TIM(0))

EVENTO_BUCLE:
  D1=D1+1
  IF D1=16 THEN GOTO INDIOS_AYUDA
  READ D 
  IF R1 > D THEN GOTO EVENTO_BUCLE

  ' tabla de corte
  DATA 6,11,13,15,17,22,32,35,37,42,44,54,64,69,95
  IF D1<=10 THEN
    SELECT CASE D1
      CASE 1:
        GOTO EV_CARRO_ROTO
      CASE 2:
        GOTO EV_BUEY_PATA
      CASE 3:
        GOTO EV_HIJA_BRAZO
      CASE 4:
        GOTO EV_BUEY_PERDIDO
      CASE 5:
        GOTO EV_HIJO_PERDIDO
      CASE 6:
        GOTO EV_AGUA_INSEGURA
      CASE 7:
        GOTO EV_LLUVIAS
      CASE 8:
        GOTO EV_BANDIDOS
      CASE 9:
        GOTO EV_INCENDIO
      CASE 10:
       GOTO EV_NIEBLA
    END SELECT
  ELSE
    SELECT CASE (D1-10)
      CASE 1:
        GOTO EV_SERPIENTE
      CASE 2: 
        GOTO EV_RIO_ENLODADO
      CASE 3: 
        GOTO EV_ANIMALES_SALVAJES
      CASE 4:
        GOTO EV_FRIO_ROPA
      CASE 5: 
        GOTO EV_GRANIZO
      CASE 6:
        GOTO EV_COMIDA_SALUD
    END SELECT
  END IF

' ---- eventos concretos ----
EV_CARRO_ROTO:
  PRINT
  PRINT "WAGON BREAKS DOWN--LOSE TIME AND"
  PRINT "SUPPLIES FIXING IT"
  M=M - 15 - 5*RND(0)
  M1=M1 - 8
  GOTO POST_EVENTO

EV_BUEY_PATA:
  PRINT
  PRINT "OX INJURES LEG---SLOWS YOU DOWN REST"
  PRINT "OF TRIP"
  M=M-25
  A=A-20
  GOTO POST_EVENTO

EV_HIJA_BRAZO:
  PRINT
  PRINT "BAD LUCK---YOUR DAUGHTER BROKE HER ARM"
  PRINT "YOU HAD TO STOP AND USE SUPPLIES TO "
  PRINT "MAKE A SLING"
  M=M - 5 - 4*RND(0)
  M1=M1 - 2 - 3*RND(0)
  GOTO POST_EVENTO

EV_BUEY_PERDIDO:
  PRINT
  PRINT "OX WANDERS OFF---SPEND TIME LOOKING"
  PRINT "FOR IT"
  M=M-17
  GOTO POST_EVENTO

EV_HIJO_PERDIDO:
  PRINT
  PRINT "YOUR SON GETS LOST---SPEND HALF THE"
  PRINT "DAY LOOKING FOR HIM"
  M=M-10
  GOTO POST_EVENTO

EV_AGUA_INSEGURA:
  PRINT
  PRINT "UNSAFE WATER--LOSE TIME LOOKING FOR"
  PRINT "CLEAN SPRING"
  M = M - 10*RND(0) - 2
  GOTO POST_EVENTO

EV_LLUVIAS:
  PRINT
  IF M>950 THEN GOTO EV_FRIO_ROPA
  PRINT "HEAVY RAINS---TIME AND SUPPLIES LOST"
  F=F-10
  B=B-500
  M1=M1-15
  M=M - 10*RND(0) - 5
  GOTO POST_EVENTO

EV_BANDIDOS:
  PRINT
  PRINT "BANDITS ATTACK"
  GOSUB SUBRUTINA_DISPARO
  B=B - 20*B1
  IF B < 0 THEN
    PRINT "YOU RAN OUT OF BULLETS"
    PRINT "THEY GET LOTS OF CASH"
    T=T/3
  ELSEIF B1 > 1 THEN
    PRINT "YOU GOT SHOT IN THE LEG AND THEY TOOK"
    PRINT "ONE OF YOUR OXEN"
    K8=1
    PRINT "BETTER HAVE A DOC LOOK AT YOUR WOUND"
    M1=M1-5
    A=A-20
  ELSE
    PRINT "QUICKEST DRAW OUTSIDE OF DODGE CITY!!!"
    PRINT "YOU GOT 'EM!"
  END IF
  GOTO POST_EVENTO

EV_INCENDIO:
  PRINT
  PRINT "THERE WAS A FIRE IN YOUR WAGON"
  PRINT "FOOD AND SUPPLIES DAMAGED"
  F=F-40
  B=B-400
  M1=M1 - RND(0)*8 - 3
  M=M-15
  GOTO POST_EVENTO

EV_NIEBLA:
  PRINT
  PRINT "LOSE YOUR WAY IN HEAVY FOG"
  PRINT "TIME IS LOST"
  M=M - 10 - 5*RND(0)
  GOTO POST_EVENTO

EV_SERPIENTE:
  PRINT
  PRINT "YOU KILLED A POISONOUS SNAKE AFTER IT"
  PRINT "BIT YOU"
  B=B-10
  M1=M1-5
  IF M1 < 0 THEN
    PRINT "YOU DIE OF SNAKEBITE SINCE YOU HAVE NO"
    PRINT "MEDICINE"
    GOTO MUERTE
  END IF
  GOTO POST_EVENTO

EV_RIO_ENLODADO:
  PRINT
  PRINT "WAGON GETS SWAMPED FORDING RIVER"
  PRINT "LOSE FOOD AND CLOTHES"
  F=F-30
  C=C-20
  M=M - 20 - 20*RND(0)
  GOTO POST_EVENTO

EV_ANIMALES_SALVAJES:
  PRINT
  PRINT "WILD ANIMALS ATTACK!"
  GOSUB SUBRUTINA_DISPARO
  IF B<=39 THEN
    PRINT "YOU WERE TOO LOW ON BULLETS"
    PRINT "THE WOLVES OVERPOWERED YOU"
    K8=1
    GOTO MUERTE_L2
  END IF
  IF B1<=2 THEN
    PRINT "NICE SHOOTIN' PARDNER---THEY DIDN'T"
    PRINT "GET MUCH"
  ELSE
    PRINT "SLOW ON THE DRAW"
    PRINT "THEY GOT AT YOUR FOOD AND CLOTHES"
  END IF
  B = B - 20*B1
  C = C - B1*4
  F = F - B1*8
  GOTO POST_EVENTO

EV_FRIO_ROPA:
  PRINT
  PRINT "COLD WEATHER---BRRRRRRR!---YOU"
  IF C > 22 + 4*RND(0) THEN
    PRINT "HAVE ENOUGH CLOTHING TO KEEP YOU WARM"
    PRINT "caliente."
    GOTO POST_EVENTO
  ELSE
    PRINT "DON'T HAVE ENOUGH CLOTHING TO KEEP"
    PRINT "YOU WARM"
    C1=1
    GOTO SUBRUTINA_ENFERMEDAD
  END IF

EV_GRANIZO:
  PRINT
  PRINT "HAIL STORM---SUPPLIES DAMAGED"
  M = M - 5 - RND(0)*10
  B = B - 200
  M1 = M1 - 4 - RND(0)*3
  GOTO POST_EVENTO

EV_COMIDA_SALUD:
  IF E=1 THEN GOTO SUBRUTINA_ENFERMEDAD
  IF E=3 THEN
    IF RND(0) < .5 THEN GOTO SUBRUTINA_ENFERMEDAD
    GOTO POST_EVENTO
  END IF
  IF RND(0) > .25 THEN GOTO SUBRUTINA_ENFERMEDAD
  GOTO POST_EVENTO

INDIOS_AYUDA:
  PRINT
  PRINT "HELPFUL INDIANS SHOW YOU WHERE TO"
  PRINT "FIND MORE FOOD"
  F=F+14
  ' cae a post_evento

POST_EVENTO:
PresionarTecla
PRINT
IF M <= 950 THEN GOTO FECHA_QUINCENA
IF RND(0)*10 <= 9 - ((M/100-15)^2+72)/((M/100-15)^2+12) THEN
  PRINT "RUGGED MOUNTAINS"
  IF RND(0) <= .1 THEN
    PRINT "YOU GOT LOST"
    PRINT "LOSE VALUABLE TIME TRYING TO FIND TRAIL!"
    M=M-60
  ELSEIF RND(0) <= .11 THEN
    PRINT "WAGON DAMAGED!---LOSE TIME AND SUPPLIES"
    M1=M1-5
    B=B-200
    M=M - 20 - 30*RND(0)
  ELSE
    PRINT "THE GOING GETS SLOW"
    M = M - 45 - RND(0)/.02
  END IF
END IF

IF F1=0 THEN
  F1=1
  IF RND(0) >= .8 THEN 
    PRINT "YOU MADE IT SAFELY THROUGH SOUTH PASS"
    PRINT "NO SNOW"
  END IF
END IF

IF M>=1700 AND F2=0 THEN
  F2=1
  IF RND(0) >= .7 THEN GOTO NEVADA_PASO
END IF

IF M>950 THEN GOTO FECHA_QUINCENA
M9=1
GOTO FECHA_QUINCENA

NEVADA_PASO:
  PRINT
  PRINT "BLIZZARD IN MOUNTAIN PASS"
  PRINT "TIME AND SUPPLIES LOST"
  L1=1
  F=F-25
  M1=M1-10
  B=B-300
  M=M - 30 - 40*RND(0)
  IF C < 18 + 2*RND(0) THEN GOTO SUBRUTINA_ENFERMEDAD
  GOTO POST_EVENTO ' regresar a flujo normal

'--------------------------------------
' MORIR / GAME OVER
'--------------------------------------
SIN_COMIDA:
  PRINT
  PRINT "YOU RAN OUT OF FOOD AND STARVED TO DEATH"
  GOTO MUERTE

SIN_DINERO_MEDICO:
  PRINT
  T=0
  PRINT "YOU CAN'T AFFORD A DOCTOR"
  GOTO MUERTE_L2

MUERTE_L2:
  PRINT
  PRINT "YOU RAN OUT MEDICAL SUPPLIES"
  PRINT
  PRINT "YOU DIED OF ";
  IF K8=1 THEN
    PRINT "INJURIES"
  ELSE
    PRINT "PNEUMONIA"
  END IF

MUERTE:
  PresionarTecla
  CLS
  Titulo("Q.E.P.D.")
  PRINT
  PRINT "DUE TO YOUR UNFORTUNATE SITUATION, "
  PRINT "THERE ARE A FEW FORMALITIES THAT MUST"
  PRINT "BE COMPLETED."
  PRINT "WE MUST OBTAIN A MINISTER, ARRANGE A"
  PRINT "FANCY FUNERAL, AND INFORM YOUR NEAREST"
  PRINT "RELATIVES. SURELY YOUR AUNT NELLIE IN"
  PRINT "ST. LOUIS IS WORRIED ABOUT THIS"
  PRINT "SITUATION."
  PRINT

  Titulo("TELEGRAM:")
  PRINT
  PRINT "WE THANK YOU FOR THIS INFORMATION AND"
  PRINT "WE ARE SORRY YOU DIDN'T MAKE IT TO THE"
  PRINT "GREAT TERRITORY OF OREGON"
  PRINT "BETTER LUCK NEXT TIME"
  PRINT
  PRINT CENTRAR$("SINCERELY,")
  PRINT
  PRINT CENTRAR$("THE OREGON CITY CHAMBER")
  PRINT CENTRAR$("OF COMMERCE")
  PresionarTecla
  CLS
  FINAL_DEL_JUEGO

'--------------------------------------
' LLEGADA FINAL
'--------------------------------------
LLEGADA_FINAL:
F9=(2040-M2)/(M-M2)
F=F + (1-F9)*(8+5*E)

Titulo("FELICITACIONES!")

PRINT
PRINT "YOU FINALLY ARRIVED AT OREGON CITY"
PRINT "AFTER 2040 LONG MILES---HOORAY!!!"
PRINT

F9=INT(F9*14)
D3=D3*14 + F9
F9=F9+1
IF F9>=8 THEN F9=F9-7

fecha_aux$ = "" 

SELECT CASE F9
  CASE 1:
   fecha_aux$ = "MONDAY "
  CASE 2:
   fecha_aux$ = "TUESDAY "
  CASE 3:
   fecha_aux$ = "WEDNESDAY "
  CASE 4:
   fecha_aux$ = "THURSDAY "
  CASE 5:
   fecha_aux$ = "FRIDAY "
  CASE 6:
   fecha_aux$ = "SATURDAY "
  CASE 7:
   fecha_aux$ = "SUNDAY "
END SELECT

IF D3>124 THEN
  IF D3>155 THEN
    IF D3>185 THEN
      IF D3>216 THEN
        D3=D3-216
        fecha_aux$ = fecha_aux$ + "JULY " + STR$(D3) + " 1847"
      ELSE
        D3=D3-185
        fecha_aux$ = fecha_aux$ + STR$(D3) + " 1847"
      END IF
    ELSE
      D3=D3-155
      fecha_aux$ = fecha_aux$ +"AUGUST "+ STR$(D3) + " 1847"
    END IF
  ELSE
    D3=D3-124
    fecha_aux$ = fecha_aux$ + "SEPTEMBER " + STR$(D3) + " 1847"
  END IF
ELSE
  D3=D3-93
  fecha_aux$ = fecha_aux$ + "OCTOBER " + STR$(D3) + " 1847"
END IF

COLOR RGB(white) : 
PRINT STRING$(40,"_")
PRINT 
Titulo(fecha_aux$)
PRINT

PRINT
PRINT " FOOD  BULLETS  CLOTH  MISC.SUPP.  CASH"
IF B<0 THEN B=0
IF C<0 THEN C=0
IF M1<0 THEN M1=0
IF T<0 THEN T=0
IF F<0 THEN F=0
PRINT TAB(2);F;
PRINT TAB(9);B;
PRINT TAB(17);C;
PRINT TAB(25);M1;
PRINT TAB(35);"$";T
PRINT
PresionarTecla

Titulo("TELEGRAM:")
PRINT
PRINT CENTER$("PRESIDENT JAMES K. POLK SENDS YOU HIS")
PRINT CENTER$(" HEARTIEST CONGRATULATIONS")
PRINT CENTER$("AND WISHES YOU A PROSPEROUS LIFE AHEAD")
PRINT CENTER$("AT YOUR NEW HOME")
PRINT
COLOR RGB(green)
FINAL_DEL_JUEGO


'--------------------------------------
' SUBRUTINAS
'--------------------------------------
ENTRADA_COMPRA:
  INPUT P
  IF P<0 THEN RETURN
  T=T-P
  IF T < 0 THEN
    PRINT "YOU DON'T HAVE THAT MUCH--KEEP YOUR"
    PRINT "SPENDING DOWN"
    T=T+P
    P=0
  END IF
RETURN

'--------------------------------------
SUBRUTINA_DISPARO:
  PRINT
  PRINT "TYPE BANG";
  B2 = 7
  TIMER = 0
  INPUT Cx$
  B1 = TIMER / 1000.0
  PRINT
  IF UCASE$(Cx$) <> "BANG" OR B1 > B2 THEN
    B1 = B2 
  END IF
RETURN

'--------------------------------------
SUBRUTINA_ENFERMEDAD:
  IF 100*RND(0) < 10 + 35*(E-1) THEN
    PRINT "MILD ILLNESS---MEDICINE USED"
    M=M-5
    M1=M1-2
    GOTO ENF_SALIDA
  END IF

  IF 100*RND(0) < 100 - (40/4^(E-1)) THEN
    PRINT "SERIOUS ILLNESS---"
    PRINT "YOU MUST STOP FOR MEDICAL ATTENTION"
    M1=M1-10
    S4=1
    GOTO ENF_SALIDA
  END IF

  PRINT "BAD ILLNESS---MEDICINE USED"
  M=M-5
  M1=M1-5

  ENF_SALIDA:
  IF M1<0 THEN GOTO MUERTE_L2
  IF L1=1 THEN
    GOTO POST_EVENTO
  ELSE
    GOTO POST_EVENTO
  END IF


'--------------------------------------
SUB FINAL_DEL_JUEGO:
  PRINT: PRINT 
  PRINT "PLAY AGAIN? (Y/N)";
  INPUT a1$
  ValidarSioNo
  IF SiNo = 0 THEN
    RUN "oregontrail.bas"
  ELSE
    END
  END IF
END SUB

'--------------------------------------
'Helpers
SUB ValidarSioNo:
  DO
    a1$=UCASE$(a1$)
    IF a1$ = "YES" OR a1$ = "Y" THEN
        SiNo = 0 
        RETURN
    END IF
    IF a1$ = "N" or a1$ = "NO" THEN
        SiNo = 1 
        RETURN
    END IF
    Beep
    INPUT a1$
  LOOP
  
END SUB

'--------------------------------------
'Centrar cadena en 40 columnas
FUNCTION CENTRAR$(T$)
  LOCAL L, IZQ, DER, OUTx$
  L = LEN(T$)
  IF L > 40 THEN
    ' Si es mas largo, se recorta
    T$ = LEFT$(T$,40)
    L = 40
  ENDIF
  IZQ = (40 - L) \ 2
  DER = 40 - L - IZQ
  OUTx$ = STRING$(IZQ," ") + T$ + STRING$(DER," ")
  CENTRAR$ = OUTx$
END FUNCTION

'--------------------------------------
SUB PresionarTecla
  PRINT
  PRINT "PRESS ANY KEY...";
  DO WHILE LEN(INKEY$) = 0 
  LOOP
  PRINT
END SUB

'--------------------------------------
SUB Beep
  play tone 500,500
  pause 500
  play stop
END SUB

'--------------------------------------
SUB Titulo(T$):
  COLOR RGB(gold)
  PRINT CENTRAR$(T$)
  COLOR RGB(green)
END SUB